# Generated by Django 5.1.1 on 2024-09-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Password', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Stock', models.IntegerField(blank=True, null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_img', models.CharField(blank=True, default='https://linklog.com/wp-content/uploads/2023/08/no-image.jpg', max_length=255, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Tag', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_tags',
                'managed': False,
            },
        ),
    ]
