# Generated by Django 5.1.1 on 2024-09-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_admin_groups_admin_is_active_admin_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='Password',
        ),
    ]
