# Generated by Django 5.1.1 on 2024-09-18 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Total_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('P_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Method', models.CharField(max_length=50)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
            options={
                'unique_together': {('Product_ID', 'Order_ID')},
            },
        ),
    ]
