# Generated by Django 5.1.1 on 2024-09-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'order_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Total_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('P_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Method', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
