# Generated by Django 5.1.1 on 2024-09-18 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=255)),
                ('MName', models.CharField(blank=True, max_length=255, null=True)),
                ('LName', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Cart_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'unique_together': {('CustomerID', 'Cart_ID')},
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Cart_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.cart')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'unique_together': {('Product_ID', 'CustomerID', 'Cart_ID')},
            },
        ),
    ]
