# Generated by Django 5.1.1 on 2024-09-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Cart_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cart_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=255)),
                ('MName', models.CharField(blank=True, max_length=255, null=True)),
                ('LName', models.CharField(max_length=255)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
