# Generated by Django 5.1.1 on 2024-09-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_groups_customer_is_active_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Password',
        ),
    ]
